name: jimmy_development
description: Common Package
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Font List  https://fonts.google.com/
  google_fonts: ^2.1.0

  # FireBase
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_messaging: ^10.0.4
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_dynamic_links: ^4.0.4

  # Kakao Service
  kakao_flutter_sdk: ^0.7.0

  # Naver Service
  flutter_naver_login: ^1.2.4

  carousel_slider: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  webview_flutter: ^2.0.12
  smooth_page_indicator: ^0.2.3
  flutter_rating_bar: ^4.0.0
  animated_text_kit: ^4.2.1
  scroll_snap_list: ^0.8.4
  table_calendar: ^3.0.3
  provider: ^6.0.1
  url_launcher: ^6.0.9
  share_plus: ^2.1.4
  google_maps_flutter: ^2.0.6
  image_picker: ^0.8.3+3
  flutter_native_image: ^0.0.6+1
  expandable: ^5.0.1
  bottom_bar_with_sheet: ^2.1.0
  package_info_plus: ^1.3.1
  flutter_spinkit: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
